### PR TITLE
Update endpoints and tests based on new model

### LINKED ISSUE #10: Implement API Endpoints and Update Tests
Implement the two `\applicant` and `\predict` routes, with a total of 3 endpoints (`POST` and `GET` for `\applicant`; `GET` for `\predict`), and update the tests in `test_routes.py` accordingly.

### PR DESCRIPTION
**Pull request by gracexin2003**
Add all the new attributes to the `/applicants` and `/predict` routes, and update the tests based on their new functionalities

### CODE REVIEW

**Comment by gracexin2003** [comment]
All the tests are passing now!! Lmk your thoughts and if I should document/change anything :)

**Review by junjasminenie — COMMENTED** [review]
Hey Grace! This looks good to me. I just pulled this and the tests passed on my local repository as well so thank you!

**Review by lywu-andrew — APPROVED** [review]
I've reviewed all the test cases and they all make sense with the implementation and its endpoints. Thank you for also adding a default value if the user has not made a POST request to applicants yet. Nice job on organizing the variables and adding in the applicable status codes.

**Review by junjasminenie — APPROVED** [review]

**Review by junjasminenie — COMMENTED** [review]
This looks good thanks Laura for fixing the merge conflict.

**Pull request merged**
